all:
	$(MAKE) -C src_standard all

bonus:
	$(MAKE) -C src_standard bonus

clean:
	$(MAKE) -C src_standard clean

fclean:
	$(MAKE) -C src_standard fclean

re:
	$(MAKE) -C src_standard re

.PHONY: all bonus clean fclean re
